### ISSUE TITLE
error when installation

### ISSUE THREAD

**Issue by shyandsy** [dundalek/markmap#26]
when I use npm install command after git clone, there is some error message about the deprecated package browserslist.

I’m not familiar with nodejs, are there any solution?

```
D:\shyclouds\markmap (master -> origin) (markmap@0.6.0)
λ npm install
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> deasync@0.1.14 install D:\shyclouds\markmap\node_modules\deasync
> node ./build.js

`win32-x64-node-10` exists; testing
Binary is fine; exiting

> parcel-bundler@1.11.0 postinstall D:\shyclouds\markmap\node_modules\parcel-bundler
> node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"

Love Parcel? You can now donate to our open collective:
 > https://opencollective.com/parcel/donate
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1107 packages from 756 contributors and audited 12131 packages in 47.66s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

then i try to use 'npm audit fix'
```
λ npm audit fix
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

when I run the example js code, the error message shows below
```
λ node example.markdown.js
D:\shyclouds\markmap\node_modules\d3\d3.js:1935
    var xhr = {}, dispatch = d3.dispatch("beforesend", "progress", "load", "error"), headers = {}, request = new XMLHttpRequest(), responseType = null;
                                                                                                             ^

ReferenceError: XMLHttpRequest is not defined
    at d3_xhr (D:\shyclouds\markmap\node_modules\d3\d3.js:1935:110)
    at Object.text (D:\shyclouds\markmap\node_modules\d3\d3.js:1931:14)
    at Object.<anonymous> (D:\shyclouds\markmap\examples\browser\example.markdown.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by dundalek** [comment]
Hi, I think the problem is that it looks like you are trying to run an example for web browser in node. The examples in `examples/browser` are meant for the web browser, the examples in `examples/node` are for node.

**Comment by shyandsy** [comment]
hi

the error message occured when i install

look like the installation failed due to the deprecated package

发自我的 iPhone

**Comment by dundalek** [comment]
During installation it is just a warning, which is not too important. The real issue is `ReferenceError: XMLHttpRequest is not defined` which indicates that you tried to run browser examples in node.js.

**Comment by shyandsy** [comment]
i also try to view the file under browser folder

but nothing shows up, and there is a error in chrome

```
Uncaught ReferenceError: require is not defined
    at example.json.js:1
```

**Comment by dundalek** [comment]
I see, you are right. A third party package broke it. I locked down the dependency versions, which fixes it.

Please try to pull the latest commit, then run `npm install` again and after that `npm start` should work again.

**Comment by shyandsy** [comment]
it works now

a start for you , thank u

**Comment by dundalek** [comment]
great, thanks :+1:
